import "./globals.css";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import NavMenu from "@/components/nav-menu";

const poppins = Poppins({
 weight: "400",
 subsets: ["latin"],
});

const legquinne = localFont({
 variable: "--font-legquinne",
 src: "../fonts/Legquinne-Regular.otf",
});

export const metadata = {
 title: "Recipe Book",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en">
   <body
    className={`${poppins.className} ${legquinne.variable} bg-background-ni-carmel antialiased`}
   >
    {/* nav */}
    <NavMenu />

    {/* main content */}
    <main className="mt-10 mx-auto">{children}</main>
   </body>
  </html>
 );
}
