const teamsSpecialty = [
 {
  id: 1,
  img: "/images/sisig.png",
  name: "Mel's Sisig",
  cookTime: 30,
  servings: 4,
  category: "Asian",
  tags: "Pork, Sizzling, Street Food, Filipino",
  ingredients: [
   "500g pork belly",
   "2 onions, chopped",
   "3 tbsp soy sauce",
   "2 tbsp vinegar",
   "1 egg",
   "Chili peppers",
  ],
  instructions: [
   "Boil pork belly until tender, then chop into small pieces.",
   "Sauté onions until soft.",
   "Add pork, soy sauce, vinegar, and chili. Stir well.",
   "Top with egg before serving on a sizzling plate.",
  ],
 },
 {
  id: 2,
  img: "/images/adobew.png",
  name: "Michael's Adobong Manok",
  cookTime: 45,
  servings: 5,
  category: "Asian",
  tags: "Chicken, Soy Sauce, Filipino",
  ingredients: [
   "1kg chicken",
   "1/2 cup soy sauce",
   "1/3 cup vinegar",
   "6 cloves garlic, crushed",
   "2 bay leaves",
   "1 tsp peppercorns",
  ],
  instructions: [
   "Marinate meat in soy sauce, vinegar, garlic, and bay leaves for 30 minutes.",
   "Simmer marinated meat with marinade until tender.",
   "Season with pepper and reduce until sauce thickens.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 3,
  img: "/images/sinigeng.png",
  name: "Angela's Sinigang",
  cookTime: 60,
  servings: 6,
  category: "Asian",
  tags: "Soup, Sour, Tamarind, Pork, Filipino",
  ingredients: [
   "500g pork ribs",
   "1 onion, quartered",
   "2 tomatoes, quartered",
   "Tamarind soup base mix",
   "Kangkong (water spinach)",
   "String beans",
   "Radish",
  ],
  instructions: [
   "Boil pork ribs until tender.",
   "Add onions, tomatoes, and tamarind mix.",
   "Add vegetables and simmer until cooked.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 4,
  img: "/images/karekare.png",
  name: "Carmel's Beef Kare-Kare",
  cookTime: 90,
  servings: 6,
  category: "Asian",
  tags: "Beef, Oxtail, Peanut Sauce, Filipino",
  ingredients: [
   "1kg oxtail (or beef shank)",
   "2 cups peanut butter",
   "1 banana blossom",
   "String beans",
   "Eggplant",
   "Ground rice",
   "Shrimp paste (bagoong) on the side",
  ],
  instructions: [
   "Boil oxtail until tender.",
   "Add vegetables and simmer.",
   "Stir in peanut butter and ground rice until thick.",
   "Serve with shrimp paste on the side.",
  ],
 },
 {
  id: 5,
  img: "/images/pinakbet.png",
  name: "Czianel's Pinakbet",
  cookTime: 40,
  servings: 5,
  category: "Asian",
  tags: "Vegetables, Ilocano, Shrimp Paste, Filipino",
  ingredients: [
   "1/4 kg pork belly",
   "Ampalaya (bitter melon)",
   "Eggplant",
   "Okra",
   "Squash",
   "String beans",
   "Shrimp paste",
  ],
  instructions: [
   "Sauté pork belly until golden brown.",
   "Add vegetables and mix well.",
   "Season with shrimp paste and simmer until vegetables are cooked.",
   "Serve hot with rice.",
  ],
 },
];

const tasteTheWorld = [
 {
  img: "/images/img4.jpg",
  name: "Italian",
 },
 {
  img: "/images/img5.jpg",
  name: "Filipino",
 },
 {
  img: "/images/img6.jpg",
  name: "Chinese",
 },
 {
  img: "/images/img7.jpg",
  name: "American",
 },
 {
  img: "/images/img8.jpg",
  name: "Vegan",
 },
];

export const filipinoCuisines = {
 title: "Filipino",
 description: `Filipino cuisine is a comforting reflection of home, filled with flavors
      that remind us of family and tradition. From savory stews to crispy
      delights, each dish carries the essence of Filipino culture. Dive into our
      collection of Filipino favorites, guaranteed to bring back memories of
      home-cooked meals and the warm embrace of your loved ones.`,
 recipes: [
  {
   id: 1,
   img: "/images/pansitcanton.jpg",
   name: "Pancit Canton",
   cookTime: 25,
   servings: 4,
   category: "Asian",
   tags: "Noodles, Stir-Fry, Quick Meal",
   difficulty: "Easy",
   ingredients: [
    "250g pancit canton noodles",
    "200g chicken breast, sliced",
    "1 carrot, julienned",
    "1 cup cabbage, shredded",
    "2 tbsp soy sauce",
    "2 tbsp oyster sauce",
   ],
   instructions: [
    "Sauté chicken and vegetables in oil.",
    "Add soy sauce and oyster sauce.",
    "Add noodles and mix until cooked.",
    "Serve with calamansi on the side.",
   ],
  },
  {
   id: 2,
   img: "/images/laing.jpg",
   name: "Laing",
   cookTime: 35,
   servings: 4,
   category: "Asian",
   tags: "Taro Leaves, Spicy, Coconut Milk, Bicolano",
   difficulty: "Medium",
   ingredients: [
    "3 cups dried taro leaves",
    "2 cups coconut milk",
    "1 cup coconut cream",
    "1/2 cup dried fish or pork bits",
    "3 chili peppers",
    "1 onion, sliced",
   ],
   instructions: [
    "Boil coconut milk with onion and chili.",
    "Add dried fish or pork bits.",
    "Layer taro leaves on top — do not stir.",
    "Pour coconut cream and simmer until oil separates.",
   ],
  },
  {
   id: 3,
   img: "/images/lumpia.jpg",
   name: "Lumpiang Shanghai",
   cookTime: 30,
   servings: 6,
   category: "Asian",
   tags: "Fried, Pork, Appetizer, Party Food",
   difficulty: "Easy",
   ingredients: [
    "500g ground pork",
    "1 carrot, grated",
    "1 onion, chopped",
    "1 egg",
    "Spring roll wrappers",
    "Oil for frying",
   ],
   instructions: [
    "Mix pork, carrot, onion, and egg in a bowl.",
    "Wrap mixture in spring roll wrappers.",
    "Fry until golden brown.",
    "Serve with sweet chili sauce.",
   ],
  },
  {
   id: 4,
   img: "/images/tinols.jpg",
   name: "Tinolang Manok",
   cookTime: 40,
   servings: 4,
   category: "Asian",
   tags: "Chicken, Soup, Ginger, Comfort Food",
   difficulty: "Easy",
   ingredients: [
    "1 whole chicken, cut into pieces",
    "1 thumb ginger, sliced",
    "1 onion, chopped",
    "2 cloves garlic, minced",
    "2 cups green papaya, sliced",
    "2 cups malunggay leaves",
    "Fish sauce and pepper to taste",
   ],
   instructions: [
    "Sauté garlic, onion, and ginger until aromatic.",
    "Add chicken and cook until lightly browned.",
    "Pour in water and simmer until chicken is tender.",
    "Add papaya and cook until soft.",
    "Add malunggay leaves and season with fish sauce and pepper.",
   ],
  },
  {
   id: 5,
   img: "/images/bicol.jpg",
   name: "Bicol Express",
   cookTime: 35,
   servings: 4,
   category: "Asian",
   tags: "Spicy, Pork, Coconut Milk, Bicolano",
   difficulty: "Medium",
   ingredients: [
    "500g pork belly, sliced",
    "2 cups coconut milk",
    "1 cup coconut cream",
    "5 green chili peppers, sliced",
    "3 cloves garlic, minced",
    "1 onion, chopped",
    "Salt and pepper to taste",
   ],
   instructions: [
    "Sauté garlic and onion until fragrant.",
    "Add pork and cook until light brown.",
    "Pour in coconut milk and simmer until tender.",
    "Add chili peppers and coconut cream.",
    "Simmer until the sauce thickens and oil separates.",
   ],
  },
  {
   id: 6,
   img: "/images/beefcaldereta.jpg",
   name: "Beef Caldereta",
   cookTime: 90,
   servings: 6,
   category: "Asian",
   tags: "Beef, Tomato Sauce, Stew, Hearty Meal",
   difficulty: "Medium",
   ingredients: [
    "1 kg beef cubes",
    "1 cup tomato sauce",
    "1 red bell pepper, sliced",
    "1 potato, cubed",
    "1 carrot, sliced",
    "1/2 cup liver spread",
    "2 cups beef broth",
   ],
   instructions: [
    "Sauté garlic and onion, then add beef and brown.",
    "Pour in tomato sauce and beef broth, simmer until tender.",
    "Add liver spread and mix well.",
    "Add vegetables and simmer until cooked.",
    "Season with salt and pepper to taste.",
   ],
  },
  {
   id: 7,
   img: "/images/chickeninasal.jpg",
   name: "Chicken Inasal",
   cookTime: 60,
   servings: 4,
   category: "Asian",
   tags: "Grilled, Chicken, Ilonggo, Savory",
   difficulty: "Medium",
   ingredients: [
    "1 kg chicken leg quarters",
    "1/2 cup vinegar",
    "1/4 cup calamansi juice",
    "1/4 cup soy sauce",
    "1/4 cup annatto oil",
    "4 cloves garlic, minced",
    "Salt and pepper to taste",
   ],
   instructions: [
    "Marinate chicken in vinegar, calamansi, soy sauce, garlic, salt, and pepper for 1 hour.",
    "Grill over medium heat while basting with annatto oil.",
    "Cook until golden brown and tender.",
    "Serve with garlic rice and dipping sauce.",
   ],
  },
  {
   id: 8,
   img: "/images/ubeputo.jpg",
   name: "Ube Puto",
   cookTime: 25,
   servings: 6,
   category: "Asian",
   tags: "Rice Cake, Steamed, Filipino Snack, Sweet, Dessert",
   difficulty: "Easy",
   ingredients: [
    "1 cup all-purpose flour",
    "1/2 cup sugar",
    "1 tbsp baking powder",
    "1 cup water or coconut milk",
    "1 egg",
    "Cheese slices for topping",
   ],
   instructions: [
    "Mix flour, sugar, and baking powder in a bowl.",
    "Add water or coconut milk and egg, then whisk until smooth.",
    "Pour into puto molds and top with cheese.",
    "Steam for 10–15 minutes or until firm.",
    "Serve warm.",
   ],
  },
 ],
};


export const italianCuisines = {
  title: "Italian",
  description: `Italian cuisine is a celebration of simplicity and bold flavor. 
  With fresh ingredients, fragrant herbs, and rich sauces, each dish tells a story 
  of tradition and passion. From comforting pasta to wood-fired pizza, enjoy the 
  timeless taste of Italy in every bite.`,
  recipes: [
    {
      id: 1,
      img: "/images/spagcarbo.jpg",
      name: "Spaghetti Carbonara",
      cookTime: 25,
      servings: 4,
      category: "Italian",
      tags: "Pasta, Creamy, Quick Meal",
      difficulty: "Medium",
      ingredients: [
        "400g spaghetti",
        "150g pancetta",
        "3 eggs",
        "1/2 cup grated Parmesan cheese",
        "Salt and black pepper",
      ],
      instructions: [
        "Cook spaghetti until al dente.",
        "Fry pancetta until crispy.",
        "Beat eggs with Parmesan and pepper.",
        "Combine pasta, pancetta, and egg mixture while hot.",
        "Serve immediately with extra cheese.",
      ],
    },
    {
      id: 2,
      img: "/images/margpizza.jpg",
      name: "Margherita Pizza",
      cookTime: 30,
      servings: 2,
      category: "Italian",
      tags: "Pizza, Vegetarian, Classic",
      difficulty: "Medium",
      ingredients: [
        "Pizza dough",
        "1/2 cup tomato sauce",
        "125g mozzarella cheese",
        "Fresh basil leaves",
        "Olive oil",
      ],
      instructions: [
        "Spread tomato sauce on pizza dough.",
        "Top with mozzarella and basil leaves.",
        "Drizzle with olive oil.",
        "Bake at 220°C for 10–12 minutes.",
      ],
    },
    {
      id: 3,
      img: "/images/lasagna.jpg",
      name: "Lasagna",
      cookTime: 75,
      servings: 6,
      category: "Italian",
      tags: "Pasta, Baked, Comfort Food",
      difficulty: "Hard",
      ingredients: [
        "12 lasagna noodles",
        "500g ground beef",
        "2 cups tomato sauce",
        "2 cups béchamel sauce",
        "1 cup mozzarella cheese",
      ],
      instructions: [
        "Cook beef with tomato sauce.",
        "Layer noodles, meat sauce, béchamel, and cheese.",
        "Repeat layers and top with cheese.",
        "Bake for 40 minutes until golden.",
      ],
    },
    {
      id: 4,
      img: "/images/risotto.jpg",
      name: "Mushroom Risotto",
      cookTime: 35,
      servings: 4,
      category: "Italian",
      tags: "Rice, Creamy, Comfort Food",
      difficulty: "Medium",
      ingredients: [
        "1 cup Arborio rice",
        "200g mushrooms, sliced",
        "1 onion, chopped",
        "1/2 cup white wine",
        "3 cups chicken broth",
      ],
      instructions: [
        "Sauté onions and mushrooms in butter.",
        "Add rice and cook for 2 minutes.",
        "Gradually add broth while stirring.",
        "Add wine and cook until creamy.",
      ],
    },
    {
      id: 5,
      img: "/images/bruschetta.jpg",
      name: "Bruschetta",
      cookTime: 15,
      servings: 4,
      category: "Italian",
      tags: "Appetizer, Bread, Tomato, Garlic",
      difficulty: "Easy",
      ingredients: [
        "8 slices of baguette",
        "2 tomatoes, diced",
        "2 cloves garlic, minced",
        "Olive oil",
        "Fresh basil",
      ],
      instructions: [
        "Toast bread slices.",
        "Mix tomatoes, garlic, basil, and olive oil.",
        "Spoon mixture over toasted bread.",
      ],
    },
    {
      id: 6,
      img: "/images/tiramisu.jpg",
      name: "Tiramisu",
      cookTime: 30,
      servings: 6,
      category: "Italian",
      tags: "Dessert, Coffee, Creamy",
      difficulty: "Medium",
      ingredients: [
        "200g ladyfingers",
        "1 cup brewed espresso",
        "250g mascarpone cheese",
        "2 eggs",
        "Cocoa powder for dusting",
      ],
      instructions: [
        "Beat eggs and mascarpone until creamy.",
        "Dip ladyfingers in espresso and layer in dish.",
        "Spread mascarpone mixture on top.",
        "Repeat and dust with cocoa powder.",
      ],
    },
    {
      id: 7,
      img: "/images/pesto.jpg",
      name: "Pesto Pasta",
      cookTime: 20,
      servings: 4,
      category: "Italian",
      tags: "Pasta, Basil, Vegetarian",
      difficulty: "Easy",
      ingredients: [
        "400g pasta",
        "1 cup fresh basil leaves",
        "1/4 cup pine nuts",
        "1/4 cup Parmesan cheese",
        "Olive oil",
      ],
      instructions: [
        "Blend basil, pine nuts, Parmesan, and olive oil to make pesto.",
        "Toss with cooked pasta.",
        "Serve with extra cheese on top.",
      ],
    },
    {
      id: 8,
      img: "/images/minestrone.jpg",
      name: "Minestrone Soup",
      cookTime: 40,
      servings: 4,
      category: "Italian",
      tags: "Soup, Vegetables, Healthy",
      difficulty: "Easy",
      ingredients: [
        "1 onion, chopped",
        "1 carrot, diced",
        "1 zucchini, chopped",
        "1 can diced tomatoes",
        "1 cup pasta or beans",
      ],
      instructions: [
        "Sauté vegetables in olive oil.",
        "Add tomatoes and water or broth.",
        "Add pasta or beans and cook until tender.",
      ],
    },
  ],
};


export const chineseCuisines = {
  title: "Chinese",
  description: `Chinese cuisine blends balance, flavor, and tradition in every dish. 
  From the heat of Sichuan spices to the delicate touch of Cantonese dim sum, 
  each meal is a journey through centuries of culinary mastery.`,
  recipes: [
    {
      id: 1,
      img: "",
      name: "Sweet and Sour Pork",
      cookTime: 30,
      servings: 4,
      category: "Asian",
      tags: "Pork, Sweet, Tangy, Stir-Fry",
      difficulty: "Medium",
      ingredients: [
        "500g pork chunks",
        "1 bell pepper, chopped",
        "1 onion, chopped",
        "1/4 cup vinegar",
        "3 tbsp ketchup",
        "2 tbsp sugar",
      ],
      instructions: [
        "Fry pork until golden brown.",
        "Mix vinegar, ketchup, and sugar for sauce.",
        "Stir-fry vegetables and add sauce.",
        "Combine with pork and serve hot.",
      ],
    },
    {
      id: 2,
      img: "",
      name: "Yangzhou Fried Rice",
      cookTime: 20,
      servings: 3,
      category: "Asian",
      tags: "Rice, Quick Meal, Savory",
      difficulty: "Easy",
      ingredients: [
        "2 cups cooked rice",
        "1 egg",
        "50g ham, diced",
        "1/2 cup mixed vegetables",
        "2 tbsp soy sauce",
      ],
      instructions: [
        "Scramble egg and set aside.",
        "Stir-fry ham and vegetables.",
        "Add rice and soy sauce.",
        "Mix in scrambled egg and serve.",
      ],
    },
    {
      id: 3,
      img: "",
      name: "Chicken Chow Mein",
      cookTime: 25,
      servings: 4,
      category: "Asian",
      tags: "Noodles, Stir-Fry, Chicken",
      difficulty: "Easy",
      ingredients: [
        "250g egg noodles",
        "200g chicken breast, sliced",
        "1 carrot, julienned",
        "2 tbsp soy sauce",
        "1 tbsp oyster sauce",
      ],
      instructions: [
        "Cook noodles and set aside.",
        "Stir-fry chicken and vegetables.",
        "Add sauces and noodles, mix well.",
        "Serve hot.",
      ],
    },
    {
      id: 4,
      img: "",
      name: "Mapo Tofu",
      cookTime: 30,
      servings: 4,
      category: "Asian",
      tags: "Spicy, Tofu, Sichuan",
      difficulty: "Medium",
      ingredients: [
        "300g tofu, cubed",
        "150g ground pork",
        "2 tbsp chili bean paste",
        "2 cloves garlic, minced",
        "1 cup broth",
      ],
      instructions: [
        "Sauté garlic and pork in oil.",
        "Add chili bean paste and stir.",
        "Add tofu and broth, simmer for 10 minutes.",
      ],
    },
    {
      id: 5,
      img: "",
      name: "Pork Dumplings",
      cookTime: 45,
      servings: 6,
      category: "Asian",
      tags: "Dumplings, Pork, Appetizer",
      difficulty: "Hard",
      ingredients: [
        "300g ground pork",
        "1 cup cabbage, minced",
        "Dumpling wrappers",
        "Soy sauce and vinegar for dipping",
      ],
      instructions: [
        "Mix pork and cabbage filling.",
        "Wrap into dumpling wrappers.",
        "Steam or fry until cooked.",
      ],
    },
    {
      id: 6,
      img: "",
      name: "Spring Rolls",
      cookTime: 30,
      servings: 4,
      category: "Asian",
      tags: "Fried, Appetizer, Vegetables",
      difficulty: "Easy",
      ingredients: [
        "Spring roll wrappers",
        "1 cup mixed vegetables",
        "1 tbsp soy sauce",
        "Oil for frying",
      ],
      instructions: [
        "Wrap vegetables in spring roll wrappers.",
        "Fry until golden brown.",
        "Serve with sweet chili sauce.",
      ],
    },
    {
      id: 7,
      img: "",
      name: "Beef with Broccoli",
      cookTime: 25,
      servings: 4,
      category: "Asian",
      tags: "Beef, Stir-Fry, Healthy",
      difficulty: "Medium",
      ingredients: [
        "300g beef slices",
        "2 cups broccoli florets",
        "2 tbsp soy sauce",
        "1 tbsp oyster sauce",
        "1 tsp cornstarch",
      ],
      instructions: [
        "Marinate beef with soy sauce and cornstarch.",
        "Stir-fry beef, then add broccoli and sauces.",
        "Cook until tender.",
      ],
    },
    {
      id: 8,
      img: "",
      name: "Congee",
      cookTime: 45,
      servings: 4,
      category: "Asian",
      tags: "Rice Porridge, Comfort Food, Breakfast",
      difficulty: "Easy",
      ingredients: [
        "1 cup rice",
        "6 cups water or broth",
        "100g shredded chicken",
        "Salt, pepper, and ginger to taste",
      ],
      instructions: [
        "Boil rice in water until soft and thick.",
        "Add chicken and seasonings.",
        "Simmer for 10 more minutes and serve warm.",
      ],
    },
  ],
};


export const americanCuisines = {
  title: "American",
  description: `American cuisine is a fusion of cultures, flavors, and innovation. 
  From smoky barbecues to juicy burgers and hearty breakfasts, it celebrates diversity 
  and creativity in every bite.`,
  recipes: [
    {
      id: 1,
      img: "",
      name: "Classic Cheeseburger",
      cookTime: 20,
      servings: 2,
      category: "American",
      tags: "Beef, Grill, Sandwich",
      difficulty: "Easy",
      ingredients: [
        "2 beef patties",
        "2 burger buns",
        "2 cheese slices",
        "Lettuce, tomato, onion",
        "Ketchup and mayo",
      ],
      instructions: [
        "Grill beef patties until cooked.",
        "Assemble buns with vegetables, cheese, and condiments.",
      ],
    },
    {
      id: 2,
      img: "",
      name: "Mac and Cheese",
      cookTime: 25,
      servings: 4,
      category: "American",
      tags: "Pasta, Creamy, Cheese",
      difficulty: "Easy",
      ingredients: [
        "250g elbow macaroni",
        "2 cups milk",
        "1 cup cheddar cheese",
        "2 tbsp butter",
        "2 tbsp flour",
      ],
      instructions: [
        "Cook macaroni and drain.",
        "Make cheese sauce with butter, flour, milk, and cheese.",
        "Combine with macaroni and serve hot.",
      ],
    },
    {
      id: 3,
      img: "",
      name: "BBQ Ribs",
      cookTime: 120,
      servings: 4,
      category: "American",
      tags: "Pork, BBQ, Grilled",
      difficulty: "Medium",
      ingredients: [
        "1 kg pork ribs",
        "1 cup BBQ sauce",
        "Salt and pepper",
      ],
      instructions: [
        "Season ribs and bake for 1.5 hours.",
        "Brush with BBQ sauce and grill until caramelized.",
      ],
    },
    {
      id: 4,
      img: "",
      name: "Southern Fried Chicken",
      cookTime: 40,
      servings: 4,
      category: "American",
      tags: "Chicken, Fried, Comfort Food",
      difficulty: "Medium",
      ingredients: [
        "1 kg chicken pieces",
        "2 cups flour",
        "1 cup buttermilk",
        "Oil for frying",
        "Salt, pepper, paprika",
      ],
      instructions: [
        "Soak chicken in buttermilk.",
        "Coat in seasoned flour.",
        "Fry until crispy and golden brown.",
      ],
    },
    {
      id: 5,
      img: "",
      name: "Buttermilk Pancakes",
      cookTime: 20,
      servings: 3,
      category: "American",
      tags: "Breakfast, Sweet, Quick",
      difficulty: "Easy",
      ingredients: [
        "1 cup flour",
        "1 cup buttermilk",
        "1 egg",
        "2 tbsp sugar",
        "1 tsp baking powder",
      ],
      instructions: [
        "Mix ingredients into a batter.",
        "Cook on griddle until bubbles form.",
        "Flip and cook until golden.",
      ],
    },
    {
      id: 6,
      img: "",
      name: "Clam Chowder",
      cookTime: 45,
      servings: 4,
      category: "American",
      tags: "Soup, Seafood, Creamy",
      difficulty: "Medium",
      ingredients: [
        "1 cup clams, chopped",
        "1 potato, diced",
        "1 onion, chopped",
        "2 cups cream",
        "2 tbsp butter",
      ],
      instructions: [
        "Sauté onion and potato in butter.",
        "Add clams and cream, simmer until thick.",
      ],
    },
    {
      id: 7,
      img: "",
      name: "Grilled Steak",
      cookTime: 25,
      servings: 2,
      category: "American",
      tags: "Beef, Grill, Savory",
      difficulty: "Easy",
      ingredients: [
        "2 steaks",
        "Salt and pepper",
        "Butter and garlic for basting",
      ],
      instructions: [
        "Season steak with salt and pepper.",
        "Grill to preferred doneness, basting with butter and garlic.",
      ],
    },
    {
      id: 8,
      img: "",
      name: "Apple Pie",
      cookTime: 60,
      servings: 6,
      category: "American",
      tags: "Dessert, Sweet, Baked",
      difficulty: "Medium",
      ingredients: [
        "2 pie crusts",
        "4 apples, sliced",
        "1/2 cup sugar",
        "1 tsp cinnamon",
      ],
      instructions: [
        "Place apples with sugar and cinnamon in crust.",
        "Cover with top crust and bake at 180°C for 45 minutes.",
      ],
    },
  ],
};


export const veganCuisines = {
  title: "Vegan",
  description: `Vegan cuisine is all about creativity, health, and compassion. 
  It proves that plant-based meals can be flavorful, hearty, and satisfying 
  while respecting the planet and its creatures.`,
  recipes: [
    {
      id: 1,
      img: "",
      name: "Buddha Bowl",
      cookTime: 25,
      servings: 2,
      category: "Vegan",
      tags: "Healthy, Salad, Protein-Rich",
      difficulty: "Easy",
      ingredients: [
        "1 cup quinoa",
        "1/2 cup chickpeas",
        "1/2 avocado",
        "Mixed vegetables",
        "Tahini dressing",
      ],
      instructions: [
        "Cook quinoa and let cool.",
        "Arrange ingredients in a bowl.",
        "Drizzle with tahini dressing and serve.",
      ],
    },
    {
      id: 2,
      img: "",
      name: "Vegan Pesto Pasta",
      cookTime: 20,
      servings: 3,
      category: "Vegan",
      tags: "Pasta, Basil, Dairy-Free",
      difficulty: "Easy",
      ingredients: [
        "400g pasta",
        "1 cup basil",
        "1/4 cup cashews",
        "2 tbsp nutritional yeast",
        "Olive oil",
      ],
      instructions: [
        "Blend pesto ingredients until smooth.",
        "Toss with cooked pasta and serve.",
      ],
    },
    {
      id: 3,
      img: "",
      name: "Tofu Stir-Fry",
      cookTime: 20,
      servings: 4,
      category: "Vegan",
      tags: "Tofu, Asian, Quick Meal",
      difficulty: "Easy",
      ingredients: [
        "300g tofu, cubed",
        "1 cup mixed vegetables",
        "2 tbsp soy sauce",
        "1 tsp sesame oil",
      ],
      instructions: [
        "Pan-fry tofu until golden.",
        "Add vegetables and sauces.",
        "Stir-fry until cooked.",
      ],
    },
    {
      id: 4,
      img: "",
      name: "Lentil Curry",
      cookTime: 35,
      servings: 4,
      category: "Vegan",
      tags: "Curry, Protein-Rich, Spicy",
      difficulty: "Medium",
      ingredients: [
        "1 cup lentils",
        "1 onion, chopped",
        "1 tbsp curry powder",
        "1 cup coconut milk",
        "2 cups water",
      ],
      instructions: [
        "Sauté onion and curry powder.",
        "Add lentils, water, and coconut milk.",
        "Simmer until lentils are tender.",
      ],
    },
    {
      id: 5,
      img: "",
      name: "Vegan Tacos",
      cookTime: 20,
      servings: 3,
      category: "Vegan",
      tags: "Tacos, Mexican, Plant-Based",
      difficulty: "Easy",
      ingredients: [
        "6 taco shells",
        "1 cup black beans",
        "1/2 cup corn",
        "Lettuce, tomato, avocado",
        "Vegan mayo or salsa",
      ],
      instructions: [
        "Fill taco shells with beans and vegetables.",
        "Top with sauce and serve fresh.",
      ],
    },
    {
      id: 6,
      img: "",
      name: "Pumpkin Soup",
      cookTime: 30,
      servings: 4,
      category: "Vegan",
      tags: "Soup, Creamy, Comfort Food",
      difficulty: "Easy",
      ingredients: [
        "2 cups pumpkin, diced",
        "1 onion, chopped",
        "2 cups vegetable broth",
        "1 cup coconut milk",
      ],
      instructions: [
        "Cook pumpkin and onion in broth until soft.",
        "Blend until smooth and stir in coconut milk.",
      ],
    },
    {
      id: 7,
      img: "",
      name: "Vegan Chili",
      cookTime: 40,
      servings: 4,
      category: "Vegan",
      tags: "Beans, Spicy, Hearty",
      difficulty: "Medium",
      ingredients: [
        "1 can kidney beans",
        "1 can diced tomatoes",
        "1 onion, chopped",
        "1 tsp chili powder",
        "1 cup corn",
      ],
      instructions: [
        "Sauté onion and spices.",
        "Add beans, tomatoes, and corn.",
        "Simmer until thick.",
      ],
    },
    {
      id: 8,
      img: "",
      name: "Chia Pudding",
      cookTime: 15,
      servings: 2,
      category: "Vegan",
      tags: "Dessert, Sweet, Healthy",
      difficulty: "Easy",
      ingredients: [
        "1/4 cup chia seeds",
        "1 cup almond milk",
        "1 tbsp maple syrup",
        "Fresh fruits for topping",
      ],
      instructions: [
        "Mix chia seeds with almond milk and sweetener.",
        "Refrigerate for 4 hours or overnight.",
        "Top with fruits before serving.",
      ],
    },
  ],
};



export { teamsSpecialty, tasteTheWorld, filipinoCuisines, chineseCuisines, italianCuisines, americanCuisines, veganCuisines };
