const teamsSpecialty = [
 {
  id: 1,
  img: "/images/img3.png",
  name: "Mel's Sisig",
  cookTime: 30,
  servings: 4,
  category: "Asian",
  tags: "Pork, Sizzling, Street Food, Filipino",
  ingredients: [
   "500g pork belly",
   "2 onions, chopped",
   "3 tbsp soy sauce",
   "2 tbsp vinegar",
   "1 egg",
   "Chili peppers",
  ],
  instructions: [
   "Boil pork belly until tender, then chop into small pieces.",
   "Sauté onions until soft.",
   "Add pork, soy sauce, vinegar, and chili. Stir well.",
   "Top with egg before serving on a sizzling plate.",
  ],
 },
 {
  id: 2,
  img: "/images/img3.png",
  name: "Michael's Adobo",
  cookTime: 45,
  servings: 5,
  category: "Asian",
  tags: "Chicken, Pork, Soy Sauce, Filipino",
  ingredients: [
   "1kg chicken or pork",
   "1/2 cup soy sauce",
   "1/3 cup vinegar",
   "6 cloves garlic, crushed",
   "2 bay leaves",
   "1 tsp peppercorns",
  ],
  instructions: [
   "Marinate meat in soy sauce, vinegar, garlic, and bay leaves for 30 minutes.",
   "Simmer marinated meat with marinade until tender.",
   "Season with pepper and reduce until sauce thickens.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 3,
  img: "/images/img3.png",
  name: "Angela's Sinigang",
  cookTime: 60,
  servings: 6,
  category: "Asian",
  tags: "Soup, Sour, Tamarind, Pork, Filipino",
  ingredients: [
   "500g pork ribs",
   "1 onion, quartered",
   "2 tomatoes, quartered",
   "Tamarind soup base mix",
   "Kangkong (water spinach)",
   "String beans",
   "Radish",
  ],
  instructions: [
   "Boil pork ribs until tender.",
   "Add onions, tomatoes, and tamarind mix.",
   "Add vegetables and simmer until cooked.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 4,
  img: "/images/img3.png",
  name: "Carmel's Kare-Kare",
  cookTime: 90,
  servings: 6,
  category: "Asian",
  tags: "Beef, Oxtail, Peanut Sauce, Filipino",
  ingredients: [
   "1kg oxtail (or beef shank)",
   "2 cups peanut butter",
   "1 banana blossom",
   "String beans",
   "Eggplant",
   "Ground rice",
   "Shrimp paste (bagoong) on the side",
  ],
  instructions: [
   "Boil oxtail until tender.",
   "Add vegetables and simmer.",
   "Stir in peanut butter and ground rice until thick.",
   "Serve with shrimp paste on the side.",
  ],
 },
 {
  id: 5,
  img: "/images/img3.png",
  name: "Czianel's Pinakbet",
  cookTime: 40,
  servings: 5,
  category: "Asian",
  tags: "Vegetables, Ilocano, Shrimp Paste, Filipino",
  ingredients: [
   "1/4 kg pork belly",
   "Ampalaya (bitter melon)",
   "Eggplant",
   "Okra",
   "Squash",
   "String beans",
   "Shrimp paste",
  ],
  instructions: [
   "Sauté pork belly until golden brown.",
   "Add vegetables and mix well.",
   "Season with shrimp paste and simmer until vegetables are cooked.",
   "Serve hot with rice.",
  ],
 },
];

const tasteTheWorld = [
 {
  img: "/images/img4.jpg",
  name: "Italian",
 },
 {
  img: "/images/img5.jpg",
  name: "Filipino",
 },
 {
  img: "/images/img6.jpg",
  name: "Chinese",
 },
 {
  img: "/images/img7.jpg",
  name: "American",
 },
 {
  img: "/images/img8.jpg",
  name: "Vegan",
 },
];

export const filipinoCuisines = [
 {
  id: 1,
  img: "",
  name: "Sizzling Pork Sisig",
  cookTime: 30,
  servings: 4,
  category: "Asian",
  tags: "Pork, Sizzling, Street Food, Filipino",
  difficulty: "Medium",
  ingredients: [
   "500g pork belly",
   "2 onions, chopped",
   "3 tbsp soy sauce",
   "2 tbsp vinegar",
   "1 egg",
   "Chili peppers",
  ],
  instructions: [
   "Boil pork belly until tender, then chop into small pieces.",
   "Sauté onions until soft.",
   "Add pork, soy sauce, vinegar, and chili. Stir well.",
   "Top with egg before serving on a sizzling plate.",
  ],
 },
 {
  id: 2,
  img: "",
  name: "Adobo",
  cookTime: 45,
  servings: 5,
  category: "Asian",
  tags: "Chicken, Pork, Savory, Classic",
  difficulty: "Easy",
  ingredients: [
   "1 kg chicken or pork",
   "1/2 cup soy sauce",
   "1/3 cup vinegar",
   "5 cloves garlic, crushed",
   "2 bay leaves",
   "1 tsp peppercorns",
  ],
  instructions: [
   "Combine soy sauce, vinegar, garlic, bay leaves, and pepper in a pot.",
   "Add meat and marinate for 30 minutes.",
   "Simmer until meat is tender and sauce is reduced.",
   "Serve with steamed rice.",
  ],
 },
 {
  id: 3,
  img: "",
  name: "Kare-Kare",
  cookTime: 90,
  servings: 6,
  category: "Asian",
  tags: "Beef, Peanut Sauce, Traditional, Stew",
  difficulty: "Hard",
  ingredients: [
   "1 kg oxtail or beef shank",
   "2 tbsp annatto seeds",
   "1 cup peanut butter",
   "2 cups string beans, cut",
   "1 banana blossom, sliced",
   "1 eggplant, sliced",
   "1/4 cup shrimp paste (bagoong)",
  ],
  instructions: [
   "Boil oxtail until tender.",
   "Sauté annatto seeds for color, then remove seeds.",
   "Add peanut butter and broth to create sauce.",
   "Add vegetables and simmer until cooked.",
   "Serve with bagoong on the side.",
  ],
 },
 {
  id: 4,
  img: "",
  name: "Sinigang na Baboy",
  cookTime: 40,
  servings: 5,
  category: "Asian",
  tags: "Soup, Pork, Sour, Comfort Food",
  difficulty: "Medium",
  ingredients: [
   "1 kg pork ribs",
   "1 tomato, quartered",
   "1 onion, sliced",
   "2 cups kangkong (water spinach)",
   "2 long green chili",
   "Tamarind mix or fresh tamarind for sourness",
  ],
  instructions: [
   "Boil pork with onion and tomato until tender.",
   "Add tamarind mix for sourness.",
   "Add vegetables and cook until tender.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 5,
  img: "",
  name: "Pancit Canton",
  cookTime: 25,
  servings: 4,
  category: "Asian",
  tags: "Noodles, Stir-Fry, Quick Meal",
  difficulty: "Easy",
  ingredients: [
   "250g pancit canton noodles",
   "200g chicken breast, sliced",
   "1 carrot, julienned",
   "1 cup cabbage, shredded",
   "2 tbsp soy sauce",
   "2 tbsp oyster sauce",
  ],
  instructions: [
   "Sauté chicken and vegetables in oil.",
   "Add soy sauce and oyster sauce.",
   "Add noodles and mix until cooked.",
   "Serve with calamansi on the side.",
  ],
 },
 {
  id: 6,
  img: "",
  name: "Laing",
  cookTime: 35,
  servings: 4,
  category: "Asian",
  tags: "Taro Leaves, Spicy, Coconut Milk, Bicolano",
  difficulty: "Medium",
  ingredients: [
   "3 cups dried taro leaves",
   "2 cups coconut milk",
   "1 cup coconut cream",
   "1/2 cup dried fish or pork bits",
   "3 chili peppers",
   "1 onion, sliced",
  ],
  instructions: [
   "Boil coconut milk with onion and chili.",
   "Add dried fish or pork bits.",
   "Layer taro leaves on top — do not stir.",
   "Pour coconut cream and simmer until oil separates.",
  ],
 },
 {
  id: 7,
  img: "",
  name: "Lumpiang Shanghai",
  cookTime: 30,
  servings: 6,
  category: "Asian",
  tags: "Fried, Pork, Appetizer, Party Food",
  difficulty: "Easy",
  ingredients: [
   "500g ground pork",
   "1 carrot, grated",
   "1 onion, chopped",
   "1 egg",
   "Spring roll wrappers",
   "Oil for frying",
  ],
  instructions: [
   "Mix pork, carrot, onion, and egg in a bowl.",
   "Wrap mixture in spring roll wrappers.",
   "Fry until golden brown.",
   "Serve with sweet chili sauce.",
  ],
 },
 {
  id: 8,
  img: "",
  name: "Halo-Halo",
  cookTime: 15,
  servings: 2,
  category: "Dessert",
  tags: "Cold, Sweet, Shaved Ice, Summer Treat",
  difficulty: "Easy",
  ingredients: [
   "1 cup shaved ice",
   "1/2 cup sweetened banana, jackfruit, beans, and nata de coco",
   "1 scoop ube ice cream",
   "1 tbsp leche flan cubes",
   "1/4 cup evaporated milk",
  ],
  instructions: [
   "Layer sweetened fruits and beans in a tall glass.",
   "Add shaved ice on top.",
   "Pour evaporated milk and top with ice cream and leche flan.",
   "Mix before eating.",
  ],
 },
];

export { teamsSpecialty, tasteTheWorld, filipinoCuisines };
