const teamsSpecialty = [
 {
  id: 1,
  img: "/images/sisig.png",
  name: "Mel's Sisig",
  cookTime: 30,
  servings: 4,
  category: "Asian",
  tags: "Pork, Sizzling, Street Food, Filipino",
  ingredients: [
   "500g pork belly",
   "2 onions, chopped",
   "3 tbsp soy sauce",
   "2 tbsp vinegar",
   "1 egg",
   "Chili peppers",
  ],
  instructions: [
   "Boil pork belly until tender, then chop into small pieces.",
   "Sauté onions until soft.",
   "Add pork, soy sauce, vinegar, and chili. Stir well.",
   "Top with egg before serving on a sizzling plate.",
  ],
 },
 {
  id: 2,
  img: "/images/adobew.png",
  name: "Michael's Adobong Manok",
  cookTime: 45,
  servings: 5,
  category: "Asian",
  tags: "Chicken, Soy Sauce, Filipino",
  ingredients: [
   "1kg chicken",
   "1/2 cup soy sauce",
   "1/3 cup vinegar",
   "6 cloves garlic, crushed",
   "2 bay leaves",
   "1 tsp peppercorns",
  ],
  instructions: [
   "Marinate meat in soy sauce, vinegar, garlic, and bay leaves for 30 minutes.",
   "Simmer marinated meat with marinade until tender.",
   "Season with pepper and reduce until sauce thickens.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 3,
  img: "/images/sinigeng.png",
  name: "Angela's Sinigang",
  cookTime: 60,
  servings: 6,
  category: "Asian",
  tags: "Soup, Sour, Tamarind, Pork, Filipino",
  ingredients: [
   "500g pork ribs",
   "1 onion, quartered",
   "2 tomatoes, quartered",
   "Tamarind soup base mix",
   "Kangkong (water spinach)",
   "String beans",
   "Radish",
  ],
  instructions: [
   "Boil pork ribs until tender.",
   "Add onions, tomatoes, and tamarind mix.",
   "Add vegetables and simmer until cooked.",
   "Serve hot with rice.",
  ],
 },
 {
  id: 4,
  img: "/images/karekare.png",
  name: "Carmel's Beef Kare-Kare",
  cookTime: 90,
  servings: 6,
  category: "Asian",
  tags: "Beef, Oxtail, Peanut Sauce, Filipino",
  ingredients: [
   "1kg oxtail (or beef shank)",
   "2 cups peanut butter",
   "1 banana blossom",
   "String beans",
   "Eggplant",
   "Ground rice",
   "Shrimp paste (bagoong) on the side",
  ],
  instructions: [
   "Boil oxtail until tender.",
   "Add vegetables and simmer.",
   "Stir in peanut butter and ground rice until thick.",
   "Serve with shrimp paste on the side.",
  ],
 },
 {
  id: 5,
  img: "/images/pinakbet.png",
  name: "Czianel's Pinakbet",
  cookTime: 40,
  servings: 5,
  category: "Asian",
  tags: "Vegetables, Ilocano, Shrimp Paste, Filipino",
  ingredients: [
   "1/4 kg pork belly",
   "Ampalaya (bitter melon)",
   "Eggplant",
   "Okra",
   "Squash",
   "String beans",
   "Shrimp paste",
  ],
  instructions: [
   "Sauté pork belly until golden brown.",
   "Add vegetables and mix well.",
   "Season with shrimp paste and simmer until vegetables are cooked.",
   "Serve hot with rice.",
  ],
 },
];

const tasteTheWorld = [
 {
  img: "/images/img4.jpg",
  name: "Italian",
 },
 {
  img: "/images/img5.jpg",
  name: "Filipino",
 },
 {
  img: "/images/img6.jpg",
  name: "Chinese",
 },
 {
  img: "/images/img7.jpg",
  name: "American",
 },
 {
  img: "/images/img8.jpg",
  name: "Vegan",
 },
];

export const filipinoCuisines = [
 {
  id: 1,
  img: "/images/pansitcanton.jpg",
  name: "Pancit Canton",
  cookTime: 25,
  servings: 4,
  category: "Asian",
  tags: "Noodles, Stir-Fry, Quick Meal",
  difficulty: "Easy",
  ingredients: [
   "250g pancit canton noodles",
   "200g chicken breast, sliced",
   "1 carrot, julienned",
   "1 cup cabbage, shredded",
   "2 tbsp soy sauce",
   "2 tbsp oyster sauce",
  ],
  instructions: [
   "Sauté chicken and vegetables in oil.",
   "Add soy sauce and oyster sauce.",
   "Add noodles and mix until cooked.",
   "Serve with calamansi on the side.",
  ],
 },
 {
  id: 2,
  img: "/images/laing.jpg",
  name: "Laing",
  cookTime: 35,
  servings: 4,
  category: "Asian",
  tags: "Taro Leaves, Spicy, Coconut Milk, Bicolano",
  difficulty: "Medium",
  ingredients: [
   "3 cups dried taro leaves",
   "2 cups coconut milk",
   "1 cup coconut cream",
   "1/2 cup dried fish or pork bits",
   "3 chili peppers",
   "1 onion, sliced",
  ],
  instructions: [
   "Boil coconut milk with onion and chili.",
   "Add dried fish or pork bits.",
   "Layer taro leaves on top — do not stir.",
   "Pour coconut cream and simmer until oil separates.",
  ],
 },
 {
  id: 3,
  img: "/images/lumpia.jpg",
  name: "Lumpiang Shanghai",
  cookTime: 30,
  servings: 6,
  category: "Asian",
  tags: "Fried, Pork, Appetizer, Party Food",
  difficulty: "Easy",
  ingredients: [
   "500g ground pork",
   "1 carrot, grated",
   "1 onion, chopped",
   "1 egg",
   "Spring roll wrappers",
   "Oil for frying",
  ],
  instructions: [
   "Mix pork, carrot, onion, and egg in a bowl.",
   "Wrap mixture in spring roll wrappers.",
   "Fry until golden brown.",
   "Serve with sweet chili sauce.",
  ],
 },
 {
  id: 4,
  img: "/images/tinols.jpg",
  name: "Tinolang Manok",
  cookTime: 40,
  servings: 4,
  category: "Asian",
  tags: "Chicken, Soup, Ginger, Comfort Food",
  difficulty: "Easy",
  ingredients: [
   "1 whole chicken, cut into pieces",
   "1 thumb ginger, sliced",
   "1 onion, chopped",
   "2 cloves garlic, minced",
   "2 cups green papaya, sliced",
   "2 cups malunggay leaves",
   "Fish sauce and pepper to taste",
  ],
  instructions: [
   "Sauté garlic, onion, and ginger until aromatic.",
   "Add chicken and cook until lightly browned.",
   "Pour in water and simmer until chicken is tender.",
   "Add papaya and cook until soft.",
   "Add malunggay leaves and season with fish sauce and pepper.",
  ],
 },
 {
  id: 5,
  img: "/images/bicol.jpg",
  name: "Bicol Express",
  cookTime: 35,
  servings: 4,
  category: "Asian",
  tags: "Spicy, Pork, Coconut Milk, Bicolano",
  difficulty: "Medium",
  ingredients: [
   "500g pork belly, sliced",
   "2 cups coconut milk",
   "1 cup coconut cream",
   "5 green chili peppers, sliced",
   "3 cloves garlic, minced",
   "1 onion, chopped",
   "Salt and pepper to taste",
  ],
  instructions: [
   "Sauté garlic and onion until fragrant.",
   "Add pork and cook until light brown.",
   "Pour in coconut milk and simmer until tender.",
   "Add chili peppers and coconut cream.",
   "Simmer until the sauce thickens and oil separates.",
  ],
 },
 {
  id: 6,
  img: "/images/beefcaldereta.jpg",
  name: "Beef Caldereta",
  cookTime: 90,
  servings: 6,
  category: "Asian",
  tags: "Beef, Tomato Sauce, Stew, Hearty Meal",
  difficulty: "Medium",
  ingredients: [
   "1 kg beef cubes",
   "1 cup tomato sauce",
   "1 red bell pepper, sliced",
   "1 potato, cubed",
   "1 carrot, sliced",
   "1/2 cup liver spread",
   "2 cups beef broth",
  ],
  instructions: [
   "Sauté garlic and onion, then add beef and brown.",
   "Pour in tomato sauce and beef broth, simmer until tender.",
   "Add liver spread and mix well.",
   "Add vegetables and simmer until cooked.",
   "Season with salt and pepper to taste.",
  ],
 },
 {
  id: 7,
  img: "/images/chickeninasal.jpg",
  name: "Chicken Inasal",
  cookTime: 60,
  servings: 4,
  category: "Asian",
  tags: "Grilled, Chicken, Ilonggo, Savory",
  difficulty: "Medium",
  ingredients: [
   "1 kg chicken leg quarters",
   "1/2 cup vinegar",
   "1/4 cup calamansi juice",
   "1/4 cup soy sauce",
   "1/4 cup annatto oil",
   "4 cloves garlic, minced",
   "Salt and pepper to taste",
  ],
  instructions: [
   "Marinate chicken in vinegar, calamansi, soy sauce, garlic, salt, and pepper for 1 hour.",
   "Grill over medium heat while basting with annatto oil.",
   "Cook until golden brown and tender.",
   "Serve with garlic rice and dipping sauce.",
  ],
 },
 {
  id: 8,
  img: "/images/ubeputo.jpg",
  name: "Ube Puto",
  cookTime: 25,
  servings: 6,
  category: "Asian",
  tags: "Rice Cake, Steamed, Filipino Snack, Sweet, Dessert",
  difficulty: "Easy",
  ingredients: [
   "1 cup all-purpose flour",
   "1/2 cup sugar",
   "1 tbsp baking powder",
   "1 cup water or coconut milk",
   "1 egg",
   "Cheese slices for topping",
  ],
  instructions: [
   "Mix flour, sugar, and baking powder in a bowl.",
   "Add water or coconut milk and egg, then whisk until smooth.",
   "Pour into puto molds and top with cheese.",
   "Steam for 10–15 minutes or until firm.",
   "Serve warm.",
  ],
 },
];

export const chineseCuisines = [
 {
  id: 1,
  img: "",
  name: "Kung Pao Chicken",
  cookTime: 30,
  servings: 4,
  category: "Chinese",
  tags: "Spicy, Stir-Fry, Chicken",
  difficulty: "Medium",
  ingredients: [
   "300g chicken breast, diced",
   "1 red bell pepper, chopped",
   "1/2 cup roasted peanuts",
   "3 tbsp soy sauce",
   "1 tbsp hoisin sauce",
   "1 tbsp chili paste",
   "2 cloves garlic, minced",
   "1 tbsp cornstarch",
  ],
  instructions: [
   "Marinate chicken with soy sauce and cornstarch for 10 minutes.",
   "Stir-fry chicken until golden brown.",
   "Add garlic, bell pepper, chili paste, and sauces.",
   "Toss in peanuts and cook until thickened.",
   "Serve hot with steamed rice.",
  ],
 },
 {
  id: 2,
  img: "",
  name: "Sweet and Sour Pork",
  cookTime: 35,
  servings: 4,
  category: "Chinese",
  tags: "Sweet, Tangy, Pork",
  difficulty: "Medium",
  ingredients: [
   "300g pork loin, cubed",
   "1/2 cup pineapple chunks",
   "1 red bell pepper, sliced",
   "3 tbsp ketchup",
   "2 tbsp vinegar",
   "2 tbsp sugar",
   "2 tbsp soy sauce",
   "1 tbsp cornstarch",
  ],
  instructions: [
   "Coat pork with cornstarch and fry until golden.",
   "Mix ketchup, vinegar, sugar, and soy sauce for the sauce.",
   "Sauté bell pepper and pineapple.",
   "Add sauce and fried pork; toss until coated.",
   "Serve warm with rice.",
  ],
 },
 {
  id: 3,
  img: "",
  name: "Beef and Broccoli",
  cookTime: 25,
  servings: 3,
  category: "Chinese",
  tags: "Beef, Stir-Fry, Healthy",
  difficulty: "Easy",
  ingredients: [
   "250g beef sirloin, sliced thinly",
   "1 cup broccoli florets",
   "2 tbsp oyster sauce",
   "2 tbsp soy sauce",
   "1 tsp cornstarch",
   "2 cloves garlic, minced",
   "1 tbsp vegetable oil",
  ],
  instructions: [
   "Marinate beef in soy sauce and cornstarch for 10 minutes.",
   "Blanch broccoli until tender-crisp.",
   "Stir-fry garlic and beef until browned.",
   "Add broccoli and oyster sauce; stir well.",
   "Serve immediately with rice.",
  ],
 },
 {
  id: 4,
  img: "",
  name: "Mapo Tofu",
  cookTime: 20,
  servings: 3,
  category: "Chinese",
  tags: "Spicy, Tofu, Sichuan",
  difficulty: "Medium",
  ingredients: [
   "200g tofu, cubed",
   "100g ground pork",
   "2 tbsp doubanjiang (chili bean paste)",
   "1 tbsp soy sauce",
   "1 tsp Sichuan peppercorns",
   "2 cloves garlic, minced",
   "1 tsp cornstarch slurry",
  ],
  instructions: [
   "Sauté pork with garlic and chili bean paste.",
   "Add tofu, soy sauce, and Sichuan peppercorns.",
   "Simmer for 5 minutes.",
   "Add cornstarch slurry to thicken.",
   "Serve hot with steamed rice.",
  ],
 },
 {
  id: 5,
  img: "",
  name: "Chow Mein",
  cookTime: 20,
  servings: 4,
  category: "Chinese",
  tags: "Noodles, Quick Meal, Stir-Fry",
  difficulty: "Easy",
  ingredients: [
   "250g egg noodles",
   "1 cup bean sprouts",
   "1/2 cup cabbage, shredded",
   "1 carrot, julienned",
   "2 tbsp soy sauce",
   "1 tbsp oyster sauce",
   "2 tbsp vegetable oil",
  ],
  instructions: [
   "Boil noodles until almost done and drain.",
   "Stir-fry vegetables in oil for 2 minutes.",
   "Add noodles and sauces; toss well.",
   "Cook until noodles are slightly crisp.",
   "Serve immediately.",
  ],
 },
 {
  id: 6,
  img: "",
  name: "Hot and Sour Soup",
  cookTime: 25,
  servings: 4,
  category: "Chinese",
  tags: "Soup, Spicy, Sour",
  difficulty: "Easy",
  ingredients: [
   "4 cups chicken broth",
   "100g tofu, sliced",
   "1/4 cup mushrooms, sliced",
   "2 tbsp vinegar",
   "1 tbsp soy sauce",
   "1 tsp chili oil",
   "1 egg, beaten",
   "1 tbsp cornstarch slurry",
  ],
  instructions: [
   "Bring broth to boil and add tofu and mushrooms.",
   "Season with vinegar, soy sauce, and chili oil.",
   "Add cornstarch slurry to thicken.",
   "Slowly pour in beaten egg while stirring.",
   "Serve hot, garnished with green onions.",
  ],
 },
 {
  id: 7,
  img: "",
  name: "Fried Rice",
  cookTime: 15,
  servings: 3,
  category: "Chinese",
  tags: "Rice, Quick Meal, Comfort Food",
  difficulty: "Easy",
  ingredients: [
   "2 cups cooked rice (day-old)",
   "2 eggs, beaten",
   "1/2 cup mixed vegetables",
   "2 tbsp soy sauce",
   "1 tbsp oyster sauce",
   "1 green onion, chopped",
   "1 tbsp oil",
  ],
  instructions: [
   "Scramble eggs in a pan and set aside.",
   "Stir-fry vegetables and rice together.",
   "Add soy sauce and oyster sauce.",
   "Return eggs to the pan and mix well.",
   "Garnish with green onions before serving.",
  ],
 },
 {
  id: 8,
  img: "",
  name: "Dim Sum (Shumai)",
  cookTime: 40,
  servings: 6,
  category: "Chinese",
  tags: "Steamed, Appetizer, Pork",
  difficulty: "Hard",
  ingredients: [
   "250g ground pork",
   "100g shrimp, chopped",
   "1 tbsp soy sauce",
   "1 tbsp sesame oil",
   "1 tsp ginger, grated",
   "Wonton wrappers",
  ],
  instructions: [
   "Mix pork, shrimp, soy sauce, sesame oil, and ginger.",
   "Wrap filling in wonton wrappers leaving top open.",
   "Steam for 15–20 minutes until cooked through.",
   "Serve with soy sauce or chili oil for dipping.",
  ],
 },
];

export const italianCuisines = [
 {
  id: 1,
  img: "",
  name: "Spaghetti Carbonara",
  cookTime: 25,
  servings: 2,
  category: "Italian",
  tags: "Pasta, Creamy, Quick Meal",
  difficulty: "Medium",
  ingredients: [
   "200g spaghetti",
   "100g pancetta",
   "2 eggs",
   "1/2 cup grated Parmesan",
   "Salt and pepper to taste",
  ],
  instructions: [
   "Cook spaghetti until al dente.",
   "Fry pancetta until crispy.",
   "Whisk eggs and Parmesan together.",
   "Toss spaghetti with pancetta and remove from heat.",
   "Quickly stir in egg mixture and serve immediately.",
  ],
 },
 {
  id: 2,
  img: "",
  name: "Margherita Pizza",
  cookTime: 30,
  servings: 4,
  category: "Italian",
  tags: "Pizza, Vegetarian, Classic",
  difficulty: "Medium",
  ingredients: [
   "1 pizza dough",
   "1/2 cup tomato sauce",
   "125g mozzarella cheese",
   "Fresh basil leaves",
   "Olive oil, salt",
  ],
  instructions: [
   "Spread tomato sauce over pizza dough.",
   "Add mozzarella and basil leaves.",
   "Drizzle with olive oil and sprinkle with salt.",
   "Bake at 220°C for 10–12 minutes until crust is golden.",
  ],
 },
 {
  id: 3,
  img: "",
  name: "Lasagna",
  cookTime: 60,
  servings: 6,
  category: "Italian",
  tags: "Pasta, Baked, Comfort Food",
  difficulty: "Hard",
  ingredients: [
   "9 lasagna noodles",
   "300g ground beef",
   "2 cups tomato sauce",
   "1 cup ricotta cheese",
   "1 cup mozzarella cheese",
   "1/4 cup Parmesan cheese",
  ],
  instructions: [
   "Cook noodles and brown beef with sauce.",
   "Layer noodles, meat sauce, and cheeses in a baking dish.",
   "Repeat layers and top with mozzarella.",
   "Bake at 190°C for 35–40 minutes.",
  ],
 },
 {
  id: 4,
  img: "",
  name: "Risotto alla Milanese",
  cookTime: 35,
  servings: 3,
  category: "Italian",
  tags: "Rice, Creamy, Classic",
  difficulty: "Medium",
  ingredients: [
   "1 cup Arborio rice",
   "2 cups chicken broth",
   "1/4 cup white wine",
   "1/4 tsp saffron threads",
   "2 tbsp butter",
   "1/4 cup Parmesan cheese",
  ],
  instructions: [
   "Toast rice in butter, then add wine and saffron.",
   "Gradually add broth while stirring until creamy.",
   "Stir in Parmesan and serve hot.",
  ],
 },
 {
  id: 5,
  img: "",
  name: "Bruschetta",
  cookTime: 10,
  servings: 4,
  category: "Italian",
  tags: "Appetizer, Bread, Vegetarian",
  difficulty: "Easy",
  ingredients: [
   "1 baguette, sliced",
   "2 tomatoes, diced",
   "2 cloves garlic, minced",
   "2 tbsp olive oil",
   "Fresh basil, chopped",
  ],
  instructions: [
   "Toast bread slices until crisp.",
   "Mix tomatoes, garlic, basil, and olive oil.",
   "Spoon mixture over toasted bread and serve.",
  ],
 },
 {
  id: 6,
  img: "",
  name: "Fettuccine Alfredo",
  cookTime: 20,
  servings: 3,
  category: "Italian",
  tags: "Pasta, Creamy, Quick Meal",
  difficulty: "Easy",
  ingredients: [
   "250g fettuccine",
   "1/2 cup butter",
   "1 cup heavy cream",
   "1 cup Parmesan cheese",
   "Salt and pepper",
  ],
  instructions: [
   "Cook fettuccine until al dente.",
   "Melt butter and cream together in a pan.",
   "Add Parmesan until sauce thickens.",
   "Combine with pasta and season to taste.",
  ],
 },
 {
  id: 7,
  img: "",
  name: "Tiramisu",
  cookTime: 30,
  servings: 6,
  category: "Italian",
  tags: "Dessert, Coffee, No-Bake",
  difficulty: "Medium",
  ingredients: [
   "200g ladyfingers",
   "250g mascarpone cheese",
   "2 eggs, separated",
   "1/2 cup sugar",
   "1 cup coffee",
   "Cocoa powder for dusting",
  ],
  instructions: [
   "Beat egg yolks with sugar, then add mascarpone.",
   "Whisk egg whites and fold in.",
   "Dip ladyfingers in coffee and layer with cream mixture.",
   "Chill for 4 hours and dust with cocoa before serving.",
  ],
 },
 {
  id: 8,
  img: "",
  name: "Caprese Salad",
  cookTime: 10,
  servings: 2,
  category: "Italian",
  tags: "Salad, Fresh, Vegetarian",
  difficulty: "Easy",
  ingredients: [
   "2 tomatoes, sliced",
   "125g mozzarella cheese, sliced",
   "Fresh basil leaves",
   "2 tbsp olive oil",
   "Salt and pepper",
  ],
  instructions: [
   "Layer tomatoes and mozzarella slices alternately.",
   "Add basil leaves and drizzle with olive oil.",
   "Season with salt and pepper.",
  ],
 },
];

export const americanCuisines = [
 {
  id: 1,
  img: "",
  name: "Cheeseburger",
  cookTime: 20,
  servings: 2,
  category: "American",
  tags: "Beef, Grilled, Classic",
  difficulty: "Easy",
  ingredients: [
   "200g ground beef",
   "2 burger buns",
   "2 cheese slices",
   "Lettuce, tomato, onions",
   "Ketchup, mustard",
  ],
  instructions: [
   "Form beef into patties and grill until cooked.",
   "Add cheese to melt on top.",
   "Assemble burger with vegetables and condiments.",
  ],
 },
 {
  id: 2,
  img: "",
  name: "Buffalo Wings",
  cookTime: 30,
  servings: 4,
  category: "American",
  tags: "Chicken, Spicy, Fried",
  difficulty: "Medium",
  ingredients: [
   "500g chicken wings",
   "1/4 cup hot sauce",
   "2 tbsp butter",
   "Flour for coating",
   "Oil for frying",
  ],
  instructions: [
   "Coat wings in flour and fry until crispy.",
   "Melt butter with hot sauce and toss wings to coat.",
   "Serve with ranch or blue cheese dip.",
  ],
 },
 {
  id: 3,
  img: "",
  name: "Mac and Cheese",
  cookTime: 25,
  servings: 3,
  category: "American",
  tags: "Pasta, Creamy, Comfort Food",
  difficulty: "Easy",
  ingredients: [
   "200g elbow macaroni",
   "2 cups milk",
   "2 tbsp butter",
   "2 tbsp flour",
   "1 cup cheddar cheese",
  ],
  instructions: [
   "Cook macaroni and drain.",
   "Make roux with butter and flour, add milk.",
   "Stir in cheese until melted.",
   "Combine with macaroni and serve hot.",
  ],
 },
 {
  id: 4,
  img: "",
  name: "Clam Chowder",
  cookTime: 40,
  servings: 4,
  category: "American",
  tags: "Soup, Seafood, Creamy",
  difficulty: "Medium",
  ingredients: [
   "200g clams",
   "2 potatoes, diced",
   "1 cup milk",
   "1/2 cup cream",
   "1 onion, chopped",
   "2 tbsp butter",
  ],
  instructions: [
   "Cook onions in butter until soft.",
   "Add potatoes, clams, milk, and cream.",
   "Simmer until potatoes are tender.",
  ],
 },
 {
  id: 5,
  img: "",
  name: "BBQ Ribs",
  cookTime: 90,
  servings: 4,
  category: "American",
  tags: "Pork, BBQ, Smoky",
  difficulty: "Hard",
  ingredients: [
   "1 rack pork ribs",
   "1 cup BBQ sauce",
   "Salt, pepper, garlic powder",
  ],
  instructions: [
   "Season ribs and bake at 160°C for 1 hour.",
   "Brush with BBQ sauce and grill for 15 minutes.",
   "Serve with extra sauce.",
  ],
 },
 {
  id: 6,
  img: "",
  name: "Apple Pie",
  cookTime: 60,
  servings: 6,
  category: "American",
  tags: "Dessert, Baked, Sweet",
  difficulty: "Medium",
  ingredients: [
   "2 pie crusts",
   "5 apples, sliced",
   "1/2 cup sugar",
   "1 tsp cinnamon",
   "1 tbsp butter",
  ],
  instructions: [
   "Mix apples with sugar and cinnamon.",
   "Fill crust, cover with top crust, and seal edges.",
   "Bake at 190°C for 45 minutes.",
  ],
 },
 {
  id: 7,
  img: "",
  name: "Pancakes",
  cookTime: 15,
  servings: 3,
  category: "American",
  tags: "Breakfast, Sweet, Quick",
  difficulty: "Easy",
  ingredients: [
   "1 cup flour",
   "1 cup milk",
   "1 egg",
   "2 tbsp sugar",
   "1 tsp baking powder",
  ],
  instructions: [
   "Mix all ingredients into a smooth batter.",
   "Pour onto hot pan and cook until bubbles form.",
   "Flip and cook until golden brown.",
  ],
 },
 {
  id: 8,
  img: "",
  name: "Caesar Salad",
  cookTime: 10,
  servings: 2,
  category: "American",
  tags: "Salad, Fresh, Healthy",
  difficulty: "Easy",
  ingredients: [
   "Romaine lettuce",
   "Croutons",
   "Caesar dressing",
   "Parmesan cheese",
  ],
  instructions: [
   "Toss lettuce with dressing.",
   "Add croutons and Parmesan cheese.",
   "Serve immediately.",
  ],
 },
];

export const veganCuisines = [
 {
  id: 1,
  img: "",
  name: "Vegan Buddha Bowl",
  cookTime: 25,
  servings: 2,
  category: "Vegan",
  tags: "Healthy, Rice, Colorful",
  difficulty: "Easy",
  ingredients: [
   "1 cup quinoa or brown rice",
   "1/2 cup chickpeas",
   "1/2 avocado, sliced",
   "1/2 cup roasted sweet potato",
   "Spinach, tahini sauce",
  ],
  instructions: [
   "Cook quinoa or rice and arrange in a bowl.",
   "Add toppings and drizzle with tahini sauce.",
  ],
 },
 {
  id: 2,
  img: "",
  name: "Vegan Stir-Fry",
  cookTime: 20,
  servings: 3,
  category: "Vegan",
  tags: "Vegetables, Quick, Asian",
  difficulty: "Easy",
  ingredients: [
   "1 cup broccoli florets",
   "1 bell pepper, sliced",
   "1/2 cup tofu, cubed",
   "2 tbsp soy sauce",
   "1 tsp sesame oil",
  ],
  instructions: [
   "Stir-fry vegetables and tofu in sesame oil.",
   "Add soy sauce and cook until tender.",
  ],
 },
 {
  id: 3,
  img: "",
  name: "Vegan Chili",
  cookTime: 40,
  servings: 4,
  category: "Vegan",
  tags: "Beans, Spicy, Comfort Food",
  difficulty: "Medium",
  ingredients: [
   "1 cup kidney beans",
   "1 cup black beans",
   "1 cup tomatoes, diced",
   "1 onion, chopped",
   "1 tbsp chili powder",
  ],
  instructions: [
   "Sauté onions, then add beans and tomatoes.",
   "Add spices and simmer for 30 minutes.",
  ],
 },
 {
  id: 4,
  img: "",
  name: "Vegan Tacos",
  cookTime: 20,
  servings: 3,
  category: "Vegan",
  tags: "Mexican, Tortilla, Quick Meal",
  difficulty: "Easy",
  ingredients: [
   "6 corn tortillas",
   "1 cup lentils, cooked",
   "1/2 avocado, diced",
   "1/2 cup lettuce, shredded",
   "Salsa, lime",
  ],
  instructions: [
   "Fill tortillas with lentils and toppings.",
   "Add salsa and lime juice before serving.",
  ],
 },
 {
  id: 5,
  img: "",
  name: "Vegan Pasta Primavera",
  cookTime: 25,
  servings: 3,
  category: "Vegan",
  tags: "Pasta, Vegetables, Light",
  difficulty: "Easy",
  ingredients: [
   "200g pasta",
   "1 zucchini, sliced",
   "1 bell pepper, sliced",
   "2 tbsp olive oil",
   "1 tsp Italian seasoning",
  ],
  instructions: [
   "Cook pasta and sauté vegetables in olive oil.",
   "Mix together and season with herbs.",
  ],
 },
 {
  id: 6,
  img: "",
  name: "Vegan Curry",
  cookTime: 30,
  servings: 4,
  category: "Vegan",
  tags: "Spicy, Coconut, Indian",
  difficulty: "Medium",
  ingredients: [
   "1 cup chickpeas",
   "1 cup coconut milk",
   "1 tbsp curry powder",
   "1 potato, cubed",
   "1 onion, chopped",
  ],
  instructions: [
   "Sauté onion and curry powder.",
   "Add potato, chickpeas, and coconut milk.",
   "Simmer until thick and creamy.",
  ],
 },
 {
  id: 7,
  img: "",
  name: "Vegan Pancakes",
  cookTime: 15,
  servings: 3,
  category: "Vegan",
  tags: "Breakfast, Sweet, Dairy-Free",
  difficulty: "Easy",
  ingredients: [
   "1 cup flour",
   "1 cup almond milk",
   "1 tbsp maple syrup",
   "1 tsp baking powder",
   "1 tbsp oil",
  ],
  instructions: [
   "Mix all ingredients into smooth batter.",
   "Cook on a non-stick pan until golden on both sides.",
  ],
 },
 {
  id: 8,
  img: "",
  name: "Vegan Chocolate Mousse",
  cookTime: 10,
  servings: 2,
  category: "Vegan",
  tags: "Dessert, Chocolate, No-Bake",
  difficulty: "Easy",
  ingredients: [
   "1 ripe avocado",
   "2 tbsp cocoa powder",
   "2 tbsp maple syrup",
   "1/4 cup almond milk",
  ],
  instructions: [
   "Blend all ingredients until smooth.",
   "Chill for 30 minutes before serving.",
  ],
 },
];





export { teamsSpecialty, tasteTheWorld, filipinoCuisines, chineseCuisines, italianCuisines, americanCuisines, veganCuisines };
